// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: protocols/messages.proto

package gotes3mp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawDiscordStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDiscordStruct) Reset() {
	*x = RawDiscordStruct{}
	mi := &file_protocols_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDiscordStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDiscordStruct) ProtoMessage() {}

func (x *RawDiscordStruct) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDiscordStruct.ProtoReflect.Descriptor instead.
func (*RawDiscordStruct) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RawDiscordStruct) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RawDiscordStruct) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *RawDiscordStruct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSync) Reset() {
	*x = ServerSync{}
	mi := &file_protocols_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSync) ProtoMessage() {}

func (x *ServerSync) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSync.ProtoReflect.Descriptor instead.
func (*ServerSync) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ServerSync) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ServerSync) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerSync) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerSync) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// Messages related to responses and commands
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Data          map[string]string      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_protocols_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BaseResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *BaseResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BaseResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BaseResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BaseResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Required      bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandArg) Reset() {
	*x = CommandArg{}
	mi := &file_protocols_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandArg) ProtoMessage() {}

func (x *CommandArg) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandArg.ProtoReflect.Descriptor instead.
func (*CommandArg) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CommandArg) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *CommandArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandArg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CommandData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Args          []*CommandArg          `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandData) Reset() {
	*x = CommandData{}
	mi := &file_protocols_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandData) ProtoMessage() {}

func (x *CommandData) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandData.ProtoReflect.Descriptor instead.
func (*CommandData) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CommandData) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandData) GetArgs() []*CommandArg {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data          *CommandData           `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_protocols_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommandResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CommandResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CommandResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CommandResponse) GetData() *CommandData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DiscordSlashCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Data          *CommandData           `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordSlashCommand) Reset() {
	*x = DiscordSlashCommand{}
	mi := &file_protocols_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordSlashCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordSlashCommand) ProtoMessage() {}

func (x *DiscordSlashCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordSlashCommand.ProtoReflect.Descriptor instead.
func (*DiscordSlashCommand) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DiscordSlashCommand) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *DiscordSlashCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DiscordSlashCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DiscordSlashCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DiscordSlashCommand) GetData() *CommandData {
	if x != nil {
		return x.Data
	}
	return nil
}

type Metadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ServerId       string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	JobId          string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AdditionalData map[string]string      `protobuf:"bytes,5,rep,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protocols_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Metadata) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Metadata) GetAdditionalData() map[string]string {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

// Represents a Discord embed field.
type EmbedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Inline        bool                   `protobuf:"varint,3,opt,name=inline,proto3" json:"inline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedField) Reset() {
	*x = EmbedField{}
	mi := &file_protocols_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedField) ProtoMessage() {}

func (x *EmbedField) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedField.ProtoReflect.Descriptor instead.
func (*EmbedField) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmbedField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EmbedField) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

// Represents a full Discord embed payload.
type EmbedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`    // Target Discord channel ID
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // Optional message text before embed
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                             // Embed title
	Color         uint32                 `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`                            // Color (0xRRGGBB)
	Fields        []*EmbedField          `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`                           // Embed fields
	FooterText    string                 `protobuf:"bytes,6,opt,name=footer_text,json=footerText,proto3" json:"footer_text,omitempty"` // Footer text
	FooterIcon    string                 `protobuf:"bytes,7,opt,name=footer_icon,json=footerIcon,proto3" json:"footer_icon,omitempty"` // Footer icon URL
	Timestamp     bool                   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // Whether to include a timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedPayload) Reset() {
	*x = EmbedPayload{}
	mi := &file_protocols_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedPayload) ProtoMessage() {}

func (x *EmbedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedPayload.ProtoReflect.Descriptor instead.
func (*EmbedPayload) Descriptor() ([]byte, []int) {
	return file_protocols_messages_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedPayload) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EmbedPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmbedPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmbedPayload) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *EmbedPayload) GetFields() []*EmbedField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EmbedPayload) GetFooterText() string {
	if x != nil {
		return x.FooterText
	}
	return ""
}

func (x *EmbedPayload) GetFooterIcon() string {
	if x != nil {
		return x.FooterIcon
	}
	return ""
}

func (x *EmbedPayload) GetTimestamp() bool {
	if x != nil {
		return x.Timestamp
	}
	return false
}

var File_protocols_messages_proto protoreflect.FileDescriptor

const file_protocols_messages_proto_rawDesc = "" +
	"\n" +
	"\x18protocols/messages.proto\x12\x04main\"^\n" +
	"\x10RawDiscordStruct\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"p\n" +
	"\n" +
	"ServerSync\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\"\xf5\x01\n" +
	"\fBaseResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x120\n" +
	"\x04data\x18\x06 \x03(\v2\x1c.main.BaseResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\n" +
	"CommandArg\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"o\n" +
	"\vCommandData\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x04args\x18\x03 \x03(\v2\x10.main.CommandArgR\x04args\"\x9c\x01\n" +
	"\x0fCommandResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12%\n" +
	"\x04data\x18\x05 \x01(\v2\x11.main.CommandDataR\x04data\"\xa0\x01\n" +
	"\x13DiscordSlashCommand\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12%\n" +
	"\x04data\x18\x05 \x01(\v2\x11.main.CommandDataR\x04data\"\xfe\x01\n" +
	"\bMetadata\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12K\n" +
	"\x0fadditional_data\x18\x05 \x03(\v2\".main.Metadata.AdditionalDataEntryR\x0eadditionalData\x1aA\n" +
	"\x13AdditionalDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\n" +
	"EmbedField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06inline\x18\x03 \x01(\bR\x06inline\"\xfd\x01\n" +
	"\fEmbedPayload\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05color\x18\x04 \x01(\rR\x05color\x12(\n" +
	"\x06fields\x18\x05 \x03(\v2\x10.main.EmbedFieldR\x06fields\x12\x1f\n" +
	"\vfooter_text\x18\x06 \x01(\tR\n" +
	"footerText\x12\x1f\n" +
	"\vfooter_icon\x18\a \x01(\tR\n" +
	"footerIcon\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\bR\ttimestampB!Z\x1fgithub.com/hotarublaze/gotes3mpb\x06proto3"

var (
	file_protocols_messages_proto_rawDescOnce sync.Once
	file_protocols_messages_proto_rawDescData []byte
)

func file_protocols_messages_proto_rawDescGZIP() []byte {
	file_protocols_messages_proto_rawDescOnce.Do(func() {
		file_protocols_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocols_messages_proto_rawDesc), len(file_protocols_messages_proto_rawDesc)))
	})
	return file_protocols_messages_proto_rawDescData
}

var file_protocols_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protocols_messages_proto_goTypes = []any{
	(*RawDiscordStruct)(nil),    // 0: main.RawDiscordStruct
	(*ServerSync)(nil),          // 1: main.ServerSync
	(*BaseResponse)(nil),        // 2: main.BaseResponse
	(*CommandArg)(nil),          // 3: main.CommandArg
	(*CommandData)(nil),         // 4: main.CommandData
	(*CommandResponse)(nil),     // 5: main.CommandResponse
	(*DiscordSlashCommand)(nil), // 6: main.DiscordSlashCommand
	(*Metadata)(nil),            // 7: main.Metadata
	(*EmbedField)(nil),          // 8: main.EmbedField
	(*EmbedPayload)(nil),        // 9: main.EmbedPayload
	nil,                         // 10: main.BaseResponse.DataEntry
	nil,                         // 11: main.Metadata.AdditionalDataEntry
}
var file_protocols_messages_proto_depIdxs = []int32{
	10, // 0: main.BaseResponse.data:type_name -> main.BaseResponse.DataEntry
	3,  // 1: main.CommandData.args:type_name -> main.CommandArg
	4,  // 2: main.CommandResponse.data:type_name -> main.CommandData
	4,  // 3: main.DiscordSlashCommand.data:type_name -> main.CommandData
	11, // 4: main.Metadata.additional_data:type_name -> main.Metadata.AdditionalDataEntry
	8,  // 5: main.EmbedPayload.fields:type_name -> main.EmbedField
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protocols_messages_proto_init() }
func file_protocols_messages_proto_init() {
	if File_protocols_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocols_messages_proto_rawDesc), len(file_protocols_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_messages_proto_goTypes,
		DependencyIndexes: file_protocols_messages_proto_depIdxs,
		MessageInfos:      file_protocols_messages_proto_msgTypes,
	}.Build()
	File_protocols_messages_proto = out.File
	file_protocols_messages_proto_goTypes = nil
	file_protocols_messages_proto_depIdxs = nil
}
