name: Go

on:
  release:
    types: [published]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
        stable: true
      id: go
    - name: Build-Linux
      run: go build -ldflags="-X 'main.Build=${{ github.event.release.tag_name }}' -X 'main.GitCommit=$GITHUB_SHA'" -o build/goTES3MP-Linux src/*.go
    
    - name: Build-Windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags="-X 'main.Build=${{ github.event.release.tag_name }}' -X 'main.GitCommit=$GITHUB_SHA'" -o build/goTES3MP-Windows.exe src/*.go
    
    - name: Compress scripts
      uses: papeloto/action-zip@v1
      with:
        files: tes3mp/
        dest: build/tes3mp-scripts.zip
        
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          build/goTES3MP-Linux
          build/goTES3MP-Windows.exe
          build/tes3mp-scripts.zip