name: Test PR

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22
          stable: true

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./src